# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run tauri build
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
    - name: Copy MSI Artifact for Windows
      if: matrix.os == 'windows-latest'
      run: cp ./src-tauri/target/release/bundle/msi/pixi-graviton_0.0.0_x64_en-US.msi ./pixi-graviton_0.0.0_x64_en-US.msi
    - name: Upload MSI Artifact
      if: matrix.os == 'windows-latest'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./pixi-graviton_0.0.0_x64_en-US.msi
        asset_name: pixi-graviton_0.0.0_x64_en-US.msi
        asset_content_type: application/octet-stream
    - name: Copy NSIS Artifact for Windows
      if: matrix.os == 'windows-latest'
      run: cp ./src-tauri/target/release/bundle/nsis/pixi-graviton_0.0.0_x64-setup.exe ./pixi-graviton_0.0.0_x64-setup.exe
    - name: Upload NSIS Artifact
      if: matrix.os == 'windows-latest'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./pixi-graviton_0.0.0_x64-setup.exe
        asset_name: pixi-graviton_0.0.0_x64-setup.exe
        asset_content_type: application/octet-stream
    - name: Copy macOS .app Artifact
      if: matrix.os == 'macos-latest'
      run: cp -R ./src-tauri/target/release/bundle/macos/pixi-graviton.app ./pixi-graviton.app
    - name: Upload macOS .app Artifact
      if: matrix.os == 'macos-latest'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./pixi-graviton.app
        asset_name: pixi-graviton.app
        asset_content_type: application/octet-stream
    - name: Copy macOS .dmg Artifact
      if: matrix.os == 'macos-latest'
      run: cp ./src-tauri/target/release/bundle/dmg/pixi-graviton_0.0.0_aarch64.dmg ./pixi-graviton_0.0.0_aarch64.dmg
    - name: Upload macOS .dmg Artifact
      if: matrix.os == 'macos-latest'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./pixi-graviton_0.0.0_aarch64.dmg
        asset_name: pixi-graviton_0.0.0_aarch64.dmg
        asset_content_type: application/octet-stream
